### ISSUE TITLE
Dask-jobqueue gets unexpected keyword argument

### ISSUE THREAD

**Issue by ChayaSt** [MolSSI/QCFractal#282]
**Describe the bug**
When using dask to spin up a manager on an LSF cluster (CLI command `qcfractal-manager --config-file=lilac_manager_config.yaml`), I get the following error:
```
Traceback (most recent call last):
  File "/home/chayas/anaconda3/envs/qcf-manager-openff/bin/qcfractal-manager", line 11, in <module>
    load_entry_point('qcfractal', 'console_scripts', 'qcfractal-manager')()
  File "/lila/home/chayas/src/MolSSI/QCFractal/qcfractal/cli/qcfractal_manager.py", line 708, in main
    cluster = cluster_class(**dask_construct)
  File "/home/chayas/anaconda3/envs/qcf-manager-openff/lib/python3.7/site-packages/dask_jobqueue/lsf.py", line 100, in __init__
    memory_string = lsf_format_bytes_ceil(mem)
TypeError: lsf_format_bytes_ceil_with_unit() got an unexpected keyword argument 'unit'
```
**To Reproduce**
The yaml file used:
```
common:
 adapter: dask
 tasks_per_worker: 1
 cores_per_worker: 8
 memory_per_worker: 24
 max_workers: 1
 scratch_directory: $TMPDIR

server:
 fractal_uri: api.qcarchive.molssi.org:443
 username: choderalab
 password: ****

manager:
 manager_name: OpenFF_Chodera_Lilac
 queue_tag: openff
 log_file_prefix: "/home/chayas/qcarchive_manager/log.out"
 test: False
 ntests: 1
    
cluster:
 node_exclusivity: False
 scheduler: lsf 
 scheduler_options: ['-eo /home/chayas/error.sterr']
 task_startup_commands: 
     - conda activate qcf 
 walltime: "75:00"

dask:
 queue: cpuqueue
 ip: "10.230.1.20"
```
I'm using `qcfractal` version `'v0.7.1+21.g38a8f6f'` and `dask-jobqueue` version '`0.4.1'`.

**Comment by Lnaden** [comment]
Yes. This is a bug I can quickly fix,  but we have all day visitors this week so a release might take me until this evening. if you want to do a quick fix and get up and going again right now you can edit this line

https://github.com/MolSSI/QCFractal/blob/38a8f6f787454cc58ebfada25469f91bf9d815f3/qcfractal/cli/qcfractal_manager.py#L704

And change `unit=unit` to `unit_str=unit`
