### ISSUE TITLE
qcfractal-server assumes pg_ctl is provided by your linux distro

### ISSUE THREAD

**Issue by muammar** [MolSSI/QCFractal#357]
**Describe the bug**
`qcfractal-server` is assuming all Linux distros distribute `pg_ctl`. That is not the case when using Debian as can be seen here: https://wiki.debian.org/PostgreSql#pg_ctl_replacement. This might be easy to fix by just adding `pg_ctlcluster` as an alternative to `pg_ctl`.

**To Reproduce**
Try to run `qcfractal-server start` with postgres installed on Debian and you will get: 

```
muammar@jedi ~ 
  % qcfractal-server start                                               !10004
Starting a QCFractal server.

QCFractal server base folder: /home/muammar/.qca/qcfractal

>>> Examining SSL Certificates...

Autogenerated SSL certificates, clients must use 'verify=False' when connecting.

>>> Checking the PostgreSQL connection...

Could not detect a PostgreSQL from configuration options, starting a PostgreSQL server.


Could not find 'pg_ctl' in the current path. Please install PostgreSQL with 'conda install postgresql'.

Alternatively, you can install a system PostgreSQL manually, please see the following link: https://www.postgresql.org/download/

```

**Expected behavior**
`qcfractal-server` should start operating normally. 

**Additional context**
This is affecting Debian GNU/Linux. I am not sure if derivatives are affected as well but chances are high.

**Comment by dgasmith** [comment]
If I read this correctly we should be able to simply switch `pg_ctl` with `pg_ctlcluster`? We might try to make this configurable, we can make a simple fix for now.

**Comment by muammar** [comment]
Yes, something like changing this function https://github.com/MolSSI/QCFractal/blob/5ac50f9a7aad70579d23679ee76cb291c4679737/qcfractal/postgres_harness.py#L48 to check if `pg_ctlcluster` is also there and use it instead of `pg_ctl`.

**Comment by dgasmith** [comment]
You seem to have a good handle on this and can test out your solution on Debian, would you mind making a PR?

Likely something in the init that looks like:

```


if shutil.which("pg_ctl"):
    self.pg_ctl = shutil.which("pg_ctl")
elif...
else:
    raise
```

Hey good place for a Walrus operator in Python 3.8.

**Comment by muammar** [comment]
> You seem to have a good handle on this and can test out your solution on Debian, would you mind making a PR?
> 

I can do that. I will prepare a PR to close this issue :).

**Comment by dgasmith** [comment]
Thank you!

**Comment by dgasmith** [comment]
@muammar Gentle reminder here, we will likely be putting out a release sometime tomorrow.

**Comment by muammar** [comment]
> @muammar Gentle reminder here, we will likely be putting out a release sometime tomorrow.

I was working on this yesterday, and just did a commit you can see here: https://github.com/muammar/QCFractal/commit/1916e28e418de6bce2fb5cc9ba408d5ab28e6d66. This might not be the best way to solve this because in the Debian documentation it says that `pg_ctlcluster` **has** to be used. I don't have experience with postgres (I just had with MySQL and Mongo), so I have to look more into how to do this in a better way. 

However, the hack above seems to work butI am running into this issue:

```
muammar@jedi ~
  % qcfractal-server init                                                                                                                                                  !10080
Initializing QCFractal configuration.

>>> Settings found:

base_folder: /home/muammar/.qca/qcfractal
database:
  database_name: qcfractal_default
  directory: null
  host: localhost
  logfile: qcfractal_postgres.log
  own: true
  password: '**************'
  port: 5432
  username: null
fractal:
  allow_read: true
  compress_response: true
  geo_file_path: null
  heartbeat_frequency: 1800
  log_apis: false
  logfile: qcfractal_server.log
  max_active_services: 20
  name: QCFractal Server
  port: 7777
  query_limit: 1000
  security: null
  service_frequency: 60


>>> Writing settings...

>>> Setting up PostgreSQL...

Initializing the Postgresql database:
Traceback (most recent call last):
  File "/home/muammar/.local/bin//qcfractal-server", line 11, in <module>
    load_entry_point('qcfractal==0.8.0+87.g1916e28', 'console_scripts', 'qcfractal-server')()
  File "/home/muammar/.local/lib/python3.7/site-packages/qcfractal-0.8.0+87.g1916e28-py3.7.egg/qcfractal/cli/qcfractal_server.py", line 454, in main
  File "/home/muammar/.local/lib/python3.7/site-packages/qcfractal-0.8.0+87.g1916e28-py3.7.egg/qcfractal/cli/qcfractal_server.py", line 215, in server_init
  File "/home/muammar/.local/lib/python3.7/site-packages/qcfractal-0.8.0+87.g1916e28-py3.7.egg/qcfractal/postgres_harness.py", line 306, in initialize_postgres
  File "/home/muammar/.local/lib/python3.7/site-packages/qcfractal-0.8.0+87.g1916e28-py3.7.egg/qcfractal/postgres_harness.py", line 40, in _run
  File "/usr/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1436, in _execute_child
    executable = os.fsencode(executable)
  File "/usr/lib/python3.7/os.py", line 809, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

and

```
muammar@jedi ~
  % qcfractal-server start                                                                                                                                                 !10078
Starting a QCFractal server.

QCFractal server base folder: /home/muammar/.qca/qcfractal

>>> Examining SSL Certificates...

Autogenerated SSL certificates, clients must use 'verify=False' when connecting.

>>> Checking the PostgreSQL connection...

Could not detect a PostgreSQL from configuration options, starting a PostgreSQL server.

Starting the database:
pg_ctl command: ['-l', '/home/muammar/.qca/qcfractal/postgres/qcfractal_postgres.log', 'start']

Could not start the PostgreSQL server. Error below:

pg_ctl: directory "/home/muammar/.qca/qcfractal/postgres" is not a database cluster directory
```

Do you think this is now related to something else?

**Comment by dgasmith** [comment]
I would guess that this is the patch that you posted. `shutil.which` will return None if nothing is found. You might try to run `shutil.which("pg_ctlcluster")` to see what is returned since it is a perl script (should be fine, but YMMV).

**Comment by muammar** [comment]
At the point where I made the change, 

```
diff --git a/qcfractal/postgres_harness.py b/qcfractal/postgres_harness.py
index f47c400..c3eecf9 100644
--- a/qcfractal/postgres_harness.py
+++ b/qcfractal/postgres_harness.py
@@ -166,6 +166,7 @@ Alternatively, you can install a system PostgreSQL manually, please see the foll
                 break

         self.logger(f"pg_ctl command: {cmds}")
+        print(psql_cmd)
         psql_cmd = [psql_cmd, "-D", str(self.config.database_path)]
         return self._run(psql_cmd + cmds)
```

This prints:

```
/usr/lib/postgresql/11/bin/pg_ctl
```

I made some other changes https://github.com/muammar/QCFractal/commit/0f087e0152ec27a0711734fdb45b2df48263a6d6, and now I think is working now:

```
fixing permissions on existing directory /home/muammar/.qca/qcfractal/postgres ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... America/Los_Angeles
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

Success. You can now start the database server using:

    /usr/lib/postgresql/11/bin/pg_ctl -D /home/muammar/.qca/qcfractal/postgres -l logfile start


Starting the database:
pg_ctl command: ['-l', '/home/muammar/.qca/qcfractal/postgres/qcfractal_postgres.log', 'start']
waiting for server to start.... done
server started

PostgreSQL successfully started in a background process, current_status:

pg_ctl: server is running (PID: 26900)
/usr/lib/postgresql/11/bin/postgres "-D" "/home/muammar/.qca/qcfractal/postgres"

Building user information.


Database server successfully started!

>>> Initializing database schema...

Creating tables for database: postgresql://localhost:5432/qcfractal_default

Stamping Database with current version..


>>> Finishing up...

>>> Success! Please run `qcfractal-server start` to boot a FractalServer!
```

Could you test in your end, too? I will submit a PR with this.

**Comment by bennybp** [comment]
postgres detection is completely changed in v0.50 and I think it handles this use case. If it still doesn't work correctly, please open a new issue. Thanks!
