### ISSUE TITLE
Job fails to auto restart 

### ISSUE THREAD

**Issue by ChayaSt** [MolSSI/QCFractal#498]
**Describe the bug**
Job with id '9159273' failed with the following error without automatically restarting:
```
{'9925316': {'error_type': 'ManagerLost',
  'error_message': 'Caught Parsl Error:\nTraceback (most recent call last):\n  File "/home/dgasmith/miniconda/envs/qcfprod/lib/python3.7/site-packages/qcfractal/queue/parsl_adapter.py", line 18, in _get_future\n    return future.result()\n  File "/home/dgasmith/miniconda/envs/qcfprod/lib/python3.7/concurrent/futures/_base.py", line 425, in result\n    return self.__get_result()\n  File "/home/dgasmith/miniconda/envs/qcfprod/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result\n    raise self._exception\n  File "/home/dgasmith/miniconda/envs/qcfprod/lib/python3.7/site-packages/parsl/dataflow/futures.py", line 93, in parent_callback\n    res = executor_fu.result()\n  File "/home/dgasmith/miniconda/envs/qcfprod/lib/python3.7/concurrent/futures/_base.py", line 425, in result\n    return self.__get_result()\n  File "/home/dgasmith/miniconda/envs/qcfprod/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result\n    raise self._exception\n  File "/home/dgasmith/miniconda/envs/qcfprod/lib/python3.7/site-packages/parsl/dataflow/dflow.py", line 252, in handle_exec_update\n    res = future.result()\n  File "/home/dgasmith/miniconda/envs/qcfprod/lib/python3.7/concurrent/futures/_base.py", line 425, in result\n    return self.__get_result()\n  File "/home/dgasmith/miniconda/envs/qcfprod/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result\n    raise self._exception\n  File "/home/dgasmith/miniconda/envs/qcfprod/lib/python3.7/site-packages/parsl/executors/high_throughput/executor.py", line 387, in _queue_management_worker\n    s.reraise()\n  File "/home/dgasmith/miniconda/envs/qcfprod/lib/python3.7/site-packages/parsl/app/errors.py", line 163, in reraise\n    reraise(t, v, tb)\n  File "/home/dgasmith/miniconda/envs/qcfprod/lib/python3.7/site-packages/six.py", line 692, in reraise\n    raise value.with_traceback(tb)\n  File "/home/dgasmith/miniconda/envs/qcfprod/lib/python3.7/site-packages/parsl/executors/high_throughput/interchange.py", line 507, in start\n    raise ManagerLost(manager, self._ready_manager_queue[manager][\'hostname\'])\nparsl.executors.high_throughput.interchange.ManagerLost: Task failure due to loss of Manager b\'81f029db78bd\' on host ca107\n',
  'extras': None}}
```
**To Reproduce**

```
client = ptl.FractalClient()
client.query_kvstore('9925316')
```

**Expected behavior**
The job should automatically restart if the manager is lost.

**Comment by dgasmith** [comment]
Interesting that we already correctly tag this `'error_type': 'ManagerLost'`. We just need some logic to patch it up/

**Comment by dgasmith** [comment]
Discussion in #520.
