### ISSUE TITLE
QCPortal:get_records() raises KeyError unless method, keywords, and basis are included

### ISSUE THREAD

**Issue by ahurta92** [MolSSI/QCFractal#534]
**Describe the bug**
qcportal: The collection function `get_records()` raises a `KeyError` unless `method`, `keywords`, and `basis` are included in the function call.  The function only requires one positional argument `'method'` but truly requires 3 to return anything other than a `KeyError`  You can see more clearly the following 3 examples.

**To Reproduce**

```

>>> bdimer.get_records()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: get_records() missing 1 required positional argument: 'method' 
```

```
1.
>>> bdimer.get_records(method='dft')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adrian/projects/QCPortal/qcportal/collections/dataset.py", line 1554, in get_records
    raise KeyError(f"Requested query ({name}) did not match a known record.")
KeyError: 'Requested query (DFT) did not match a known record.'
```
2. 
```
>>> bdimer.get_records(method='dft',keywords='b3lyp')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adrian/projects/QCPortal/qcportal/collections/dataset.py", line 1554, in get_records
    raise KeyError(f"Requested query ({name}) did not match a known record.")
KeyError: 'Requested query (DFT-b3lyp) did not match a known record.'
```
3.
```
>>> bdimer.get_records(method='dft',basis='sto-3g')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adrian/projects/QCPortal/qcportal/collections/dataset.py", line 1554, in get_records
    raise KeyError(f"Requested query ({name}) did not match a known record.")
KeyError: 'Requested query (DFT/sto-3g) did not match a known record.'
```
```
>>> bdimer.get_records(method='dft',keywords='b3lyp',basis='sto-3g')
        record
index
Sdimer    None
PDdimer   None
Tdimer    None
TTdimer   None
```

**Expected behavior**
In 1. I would expect `get_records()` to return all records using method='dft'.
In 2. I would expect `get_records()` to include all records using `method='dft'` and `keyword='b3lyp'`
In 3. I would expect `get_records()` to include all records using `method='dft'` and `basis='sto-3g'`
**Additional context**

Here is what `get_values()` and `list_records()` returns which maybe of use.  
>>> bdimer.get_values()
```
        DFT/sto-3g-b3lyp-d3 DFT/sto-3g-b3lyp DFT/6-31g-b3lyp
Sdimer                  NaN              NaN             NaN
PDdimer                 NaN              NaN             NaN
Tdimer                  NaN              NaN             NaN
TTdimer                 NaN              NaN             NaN
>>> bdimer.list_records()
   driver program method   basis  keywords                 name
0  energy  nwchem    dft  sto-3g  b3lyp-d3  DFT/sto-3g-b3lyp-d3
1  energy  nwchem    dft  sto-3g     b3lyp     DFT/sto-3g-b3lyp
2  energy  nwchem    dft   6-31g     b3lyp      DFT/6-31g-b3lyp
```

**Comment by mattwelborn** [comment]
Thank you for this report!

**Comment by dgasmith** [comment]
@mattwelborn Do you think this will be quick? Might be nice to squeeze in as well.

**Comment by mattwelborn** [comment]
I'll look at this first thing tomorrow morning and make a determination.
