### ISSUE TITLE
Cannot connect to Fractal client server

### ISSUE THREAD

**Issue by kntkb** [MolSSI/QCFractal#719]
**Describe the bug**
Cannot connect to qcportal.FractalClient(). I get the following error:

```
Traceback (most recent call last):
  File "/Users/takabak/sandbox/test.py", line 2, in <module>
    client = ptl.FractalClient()
  File "/Users/takabak/mambaforge/envs/qcarchive/lib/python3.10/site-packages/qcportal/client.py", line 140, in __init__
    self.server_info = self._automodel_request("information", "get", {}, full_return=True).dict()
  File "/Users/takabak/mambaforge/envs/qcarchive/lib/python3.10/site-packages/qcportal/client.py", line 274, in _automodel_request
    r = self._request(rest, name, data=payload.serialize(self.encoding), timeout=timeout)
  File "/Users/takabak/mambaforge/envs/qcarchive/lib/python3.10/site-packages/qcportal/client.py", line 233, in _request
    raise ConnectionRefusedError(_connection_error_msg.format(self.address)) from None
ConnectionRefusedError: 

Could not connect to server https://api.qcarchive.molssi.org:443/, please check the address and try again.
```

**To Reproduce**
>import qcportal as ptl
>client = ptl.FractalClient()

**Comment by kntkb** [comment]
Closing issue because the server is back up
